export type FeatureGroup = "Visual" | "HUD" | "Accessibility" | "Performance" | "Profiles";
export type ChromaFeature = { id: string; name: string; group: FeatureGroup; description: string };

type Entry = [name: string, group: FeatureGroup, description: string];
const entries: Entry[] = [
  ["Theme Studio", "Visual", "Create and save a complete color surface."], ["Accent Mixer", "Visual", "Blend primary and secondary accents."], ["Warm Neutral Palette", "Visual", "Use softer neutral tones."], ["Glass Panels", "Visual", "Apply restrained translucent surfaces."], ["Soft Borders", "Visual", "Tune border visibility."], ["Depth Shadows", "Visual", "Add subtle hierarchy shadows."], ["Gradient Presets", "Visual", "Choose calm two-color backgrounds."], ["Color Temperature", "Visual", "Shift the interface cool or warm."], ["Saturation Control", "Visual", "Adjust overall color intensity."], ["Background Blur", "Visual", "Control blur behind panels."], ["Noise Grain", "Visual", "Add optional low-intensity texture."], ["Corner Radius", "Visual", "Tune card roundness."], ["Panel Density", "Visual", "Choose compact, balanced, or spacious layouts."], ["Icon Weight", "Visual", "Choose lighter or stronger icon strokes."], ["Menu Blur", "Visual", "Blur the area behind menus."], ["Theme Preview", "Visual", "Preview a theme before applying it."], ["Accent Preview", "Visual", "Preview accent changes."], ["Contrast Preview", "Accessibility", "Preview contrast changes."], ["Layout Preview", "Visual", "Preview scale and density changes."], ["Reset Visuals", "Visual", "Restore visual defaults only."],
  ["FPS Counter", "HUD", "Show the current frame rate."], ["Frame Time Graph", "HUD", "Display recent frame-time stability."], ["Keystrokes Panel", "HUD", "Show your own movement keys."], ["CPS Display", "HUD", "Show local input activity."], ["Coordinates Panel", "HUD", "Display local coordinates."], ["Direction Indicator", "HUD", "Show facing direction."], ["Biome Label", "HUD", "Display the current biome."], ["Clock Widget", "HUD", "Show local or session time."], ["Session Timer", "HUD", "Track elapsed session time."], ["Ping Display", "HUD", "Show server response time."], ["Memory Meter", "HUD", "Show allocated memory."], ["CPU Meter", "HUD", "Show client CPU load."], ["GPU Meter", "HUD", "Show graphics load when available."], ["FPS Graph", "HUD", "Plot a rolling frame-rate history."], ["Armor Status", "HUD", "Show your equipped armor durability."], ["Item Durability", "HUD", "Show selected item durability."], ["Effect Timer", "HUD", "Show timers for your own effects."], ["Cooldown Timer", "HUD", "Show configurable local cooldowns."], ["Crosshair Presets", "HUD", "Choose clean static crosshairs."], ["Crosshair Color", "HUD", "Set a high-contrast crosshair."], ["Crosshair Gap", "HUD", "Adjust crosshair spacing."], ["Crosshair Thickness", "HUD", "Adjust crosshair stroke width."], ["Crosshair Outline", "HUD", "Add an outline for bright scenes."], ["Hotbar Scale", "HUD", "Resize the hotbar."], ["Hotbar Opacity", "HUD", "Adjust hotbar transparency."], ["Chat Scale", "HUD", "Resize the chat surface."], ["Chat Background", "HUD", "Tune chat background opacity."], ["Chat Timestamps", "HUD", "Add local timestamps."], ["Chat Compact Mode", "HUD", "Reduce chat spacing."], ["Scoreboard Scale", "HUD", "Resize the scoreboard."], ["Scoreboard Background", "HUD", "Tune scoreboard transparency."], ["Tab List Scale", "HUD", "Resize the player list."], ["Tab List Columns", "HUD", "Choose a compact player-list layout."], ["Status Badges", "HUD", "Show local state badges."], ["Sync Indicator", "HUD", "Show account and Loader sync state."], ["Release Notes Panel", "HUD", "Read current release notes."],
  ["Night Contrast", "Accessibility", "Raise contrast for low-light sessions."], ["Reduced Motion", "Accessibility", "Disable non-essential transitions."], ["Large Text", "Accessibility", "Increase interface text size."], ["Readable Font", "Accessibility", "Use a high-legibility font stack."], ["Colorblind Preset", "Accessibility", "Use contrast-safe accent combinations."], ["Cursor Scale", "Accessibility", "Increase pointer emphasis."], ["Tooltip Delay", "Accessibility", "Choose when help text appears."], ["Keyboard Focus Ring", "Accessibility", "Keep keyboard focus visible."], ["Screen Reader Labels", "Accessibility", "Expose descriptive control labels."], ["Motion Intensity", "Accessibility", "Reduce hover and entrance motion."], ["Control Hints", "Accessibility", "Show short help hints."], ["Onboarding Checklist", "Accessibility", "Guide first-time local setup."], ["Telemetry Toggle", "Accessibility", "Keep optional telemetry disabled by default."],
  ["Menu Search", "Profiles", "Search settings by name."], ["Favorites", "Profiles", "Pin frequently used settings."], ["Preset Export", "Profiles", "Export a local visual profile."], ["Preset Import", "Profiles", "Import a local visual profile."], ["Profile Slots", "Profiles", "Keep separate visual profiles."], ["Profile Rename", "Profiles", "Name each profile."], ["Profile Duplicate", "Profiles", "Create a variation safely."], ["Profile Reset", "Profiles", "Restore one profile to defaults."], ["Auto Profile Select", "Profiles", "Select a profile for a local context."], ["Profile Backup", "Profiles", "Keep timestamped local backups."], ["Profile Diff", "Profiles", "Compare two local profiles."], ["Config Validation", "Profiles", "Validate imported settings."], ["Safe Defaults", "Profiles", "Start from readable settings."], ["Windowed Preset", "Profiles", "Save windowed layout settings."], ["Fullscreen Preset", "Profiles", "Save fullscreen layout settings."], ["Stream Preset", "Profiles", "Hide private account details."], ["Recording Preset", "Profiles", "Use a clean recording layout."], ["Minimal Preset", "Profiles", "Keep only essential controls visible."], ["Creator Preset", "Profiles", "Use a polished capture layout."], ["Color Snapshot", "Profiles", "Save a reusable palette snapshot."], ["Palette History", "Profiles", "Undo recent palette changes."], ["UI Scale Presets", "Profiles", "Save compact, standard, and large scales."],
  ["Low Spec Preset", "Performance", "Reduce visual overhead."], ["Balanced Preset", "Performance", "Balance visuals and performance."], ["Quality Preset", "Performance", "Prefer richer interface effects."], ["Animation Budget", "Performance", "Set a maximum animation budget."], ["Lazy Panel Render", "Performance", "Render hidden panels on demand."], ["Texture Preview Cache", "Performance", "Cache local previews."], ["Icon Cache", "Performance", "Cache interface icons."], ["Background Quality", "Performance", "Choose low, medium, or high quality."], ["Blur Quality", "Performance", "Choose cheaper or smoother blur."], ["Shadow Quality", "Performance", "Tune shadow softness."], ["Transition Quality", "Performance", "Choose minimal or full transitions."], ["Cache Cleanup", "Performance", "Remove stale local previews."], ["Startup Mode", "Performance", "Choose dashboard or last profile."], ["Startup Delay", "Performance", "Delay optional initialization."], ["Resource Monitor", "Performance", "Inspect local resource usage."], ["Frame Pacing Hint", "Performance", "Show a local pacing recommendation."], ["Render Scale", "Performance", "Adjust interface render scale."], ["Refresh Rate Hint", "Performance", "Show local display refresh information."],
];

export const CHROMA_FEATURES: ChromaFeature[] = entries.map(([name, group, description], index) => ({ id: `feature-${index + 1}`, name, group, description }));
export const FEATURE_GROUPS: FeatureGroup[] = ["Visual", "HUD", "Accessibility", "Performance", "Profiles"];
export const FEATURE_POLICY = "Visual, accessibility, profile, and performance customization only.";
export const FEATURE_VERSION = "2026.09-safe-visuals";
export const FEATURE_COUNT = CHROMA_FEATURES.length;
export const featureCatalogMetadata = { version: FEATURE_VERSION, count: FEATURE_COUNT, policy: FEATURE_POLICY } as const;
export const getFeaturesByGroup = (group: FeatureGroup) => CHROMA_FEATURES.filter(feature => feature.group === group);
export const findFeature = (query: string) => { const q = query.trim().toLowerCase(); return q ? CHROMA_FEATURES.filter(feature => `${feature.name} ${feature.description}`.toLowerCase().includes(q)) : CHROMA_FEATURES; };
export const isSafeFeatureId = (id: string) => CHROMA_FEATURES.some(feature => feature.id === id);
// Deliberately excludes combat automation, ESP, aim assistance, packet manipulation, bypasses, and other cheats.
if (CHROMA_FEATURES.length < 100) throw new Error("Safe feature catalog must contain at least 100 entries");
export default CHROMA_FEATURES;
