import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ArrowUpRight, Check, Copy, MessageCircle, ShoppingBag, Tag, Wallet, X } from "lucide-react";
import { useState } from "react";
import { PURCHASE_OFFERS, PURCHASE_PLAN_LABELS, TELEGRAM_SELLER, TELEGRAM_SELLER_URL, type PurchaseDuration, type PurchasePlan } from "@shared/purchase";

type PurchaseDialogProps = { initialPlan?: PurchasePlan; triggerLabel?: string; triggerClassName?: string; compact?: boolean };
const planOptions: PurchasePlan[] = ["base", "premium", "premium_beta"];
const durations: PurchaseDuration[] = ["month", "three_months", "six_months"];
const priceLabel = (price: number | null) => price === null ? "Цена уточняется" : `${price} ₽`;

export function PurchaseDialog({ initialPlan, triggerLabel = "Buy", triggerClassName, compact = false }: PurchaseDialogProps) {
  const [step, setStep] = useState<"method" | "funpay" | "telegram">("method");
  const [plan, setPlan] = useState<PurchasePlan>(initialPlan ?? "base");
  const [duration, setDuration] = useState<PurchaseDuration>("month");
  const [promo, setPromo] = useState("");
  const selectedOffer = PURCHASE_OFFERS.find(offer => offer.plan === plan && offer.duration === duration);
  const reset = () => { setStep("method"); setPromo(""); setPlan(initialPlan ?? "base"); setDuration("month"); };
  const openExternal = (url: string) => window.open(url, "_blank", "noopener,noreferrer");
  return <Dialog onOpenChange={open => { if (!open) reset(); }}>
    <DialogTrigger asChild><Button className={triggerClassName ?? (compact ? "h-10 rounded-xl bg-primary px-4 text-sm font-bold text-[#10150c]" : "h-11 w-full rounded-xl bg-primary font-bold text-[#10150c] hover:bg-[#d0ff73]")}>{triggerLabel}<ArrowUpRight className="ml-2 h-4 w-4" /></Button></DialogTrigger>
    <DialogContent className="max-w-xl border-white/10 bg-[#101512] p-0 text-foreground shadow-[0_30px_100px_rgba(0,0,0,.55)]">
      <div className="border-b border-white/[.08] bg-gradient-to-br from-primary/[.12] via-transparent to-transparent px-6 py-6 sm:px-7"><DialogHeader><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><ShoppingBag className="h-4 w-4" /> Chroma access</div><DialogTitle className="text-2xl tracking-[-.03em]">{step === "method" ? "Choose a purchase method" : step === "funpay" ? "Choose a plan and term" : "Purchase through Telegram"}</DialogTitle><DialogDescription className="mt-2 text-muted-foreground">{step === "method" ? "Select where you want to complete the purchase. Chroma never simulates or processes payment on this site." : step === "funpay" ? "You will be taken to the exact FunPay listing in a new tab." : `Contact ${TELEGRAM_SELLER} and complete the purchase directly in Telegram.`}</DialogDescription></DialogHeader></div>
      <div className="p-6 sm:p-7">
        {step === "method" && <div className="grid gap-3"><button onClick={() => setStep("funpay")} className="group flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left transition hover:border-primary/45 hover:bg-primary/[.06]"><div className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Wallet className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="font-semibold">FunPay</div><div className="mt-1 text-sm text-muted-foreground">Pay through FunPay using regular payment methods.</div></div><ArrowUpRight className="h-4 w-4 text-primary transition group-hover:translate-x-0.5" /></button><button onClick={() => setStep("telegram")} className="group flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left transition hover:border-primary/45 hover:bg-primary/[.06]"><div className="grid h-11 w-11 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><MessageCircle className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="font-semibold">Telegram</div><div className="mt-1 text-sm text-muted-foreground">Purchase through Telegram with a direct seller handoff.</div></div><ArrowUpRight className="h-4 w-4 text-primary transition group-hover:translate-x-0.5" /></button><div className="mt-3 rounded-xl border border-dashed border-white/10 p-4 text-xs leading-5 text-muted-foreground"><Tag className="mr-2 inline h-3.5 w-3.5 text-primary" />Have a promo code? After purchase, tell the seller: <span className="font-semibold text-foreground">I’m from [PROMO CODE]</span>.</div></div>}
        {step === "funpay" && <div className="grid gap-5"><div><div className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-muted-foreground">Plan</div><div className="grid gap-2 sm:grid-cols-3">{planOptions.map(option => <button key={option} onClick={() => setPlan(option)} className={`rounded-xl border px-3 py-3 text-left text-sm font-semibold transition ${plan === option ? "border-primary/60 bg-primary/[.1] text-primary" : "border-white/10 bg-white/[.025] text-muted-foreground hover:border-white/20"}`}>{PURCHASE_PLAN_LABELS[option]}</button>)}</div></div><div><div className="mb-3 text-xs font-bold uppercase tracking-[.16em] text-muted-foreground">Term</div><div className="grid gap-2 sm:grid-cols-3">{durations.map(option => { const offer = PURCHASE_OFFERS.find(item => item.plan === plan && item.duration === option)!; return <button key={option} onClick={() => setDuration(option)} className={`rounded-xl border px-3 py-3 text-left transition ${duration === option ? "border-primary/60 bg-primary/[.1]" : "border-white/10 bg-white/[.025] hover:border-white/20"}`}><div className={`text-sm font-semibold ${duration === option ? "text-primary" : "text-foreground"}`}>{offer.label}</div><div className="mt-1 text-xs text-muted-foreground">{priceLabel(offer.price)}</div></button>; })}</div></div><div className="rounded-2xl border border-primary/20 bg-primary/[.05] p-4"><div className="flex items-center justify-between"><div><div className="text-xs text-muted-foreground">Selected offer</div><div className="mt-1 font-semibold">{PURCHASE_PLAN_LABELS[plan]} · {selectedOffer?.label}</div></div><div className="text-2xl font-semibold text-primary">{priceLabel(selectedOffer?.price ?? null)}</div></div></div><div><label className="mb-2 block text-xs font-semibold text-muted-foreground">Promo code (optional)</label><input value={promo} onChange={event => setPromo(event.target.value)} placeholder="CHROMA2026" className="h-11 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-sm outline-none placeholder:text-muted-foreground/50 focus:border-primary/60" /></div><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={() => setStep("method")} className="text-muted-foreground">Back</Button><Button onClick={() => selectedOffer && openExternal(selectedOffer.url)} disabled={!selectedOffer} className="h-11 rounded-xl bg-primary font-bold text-[#10150c]">Go to purchase <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div><p className="text-xs leading-5 text-muted-foreground">After purchase, message the seller: <span className="font-semibold text-foreground">I’m from {promo ? `[${promo}]` : "[PROMO CODE]"}</span>. Do not send Telegram contact details through a FunPay order.</p></div>}
        {step === "telegram" && <div className="grid gap-5"><div className="rounded-2xl border border-sky-300/20 bg-sky-300/[.06] p-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><MessageCircle className="h-5 w-5" /></div><div><div className="font-semibold">Purchase through Telegram</div><div className="mt-1 text-sm text-muted-foreground">Contact {TELEGRAM_SELLER} to arrange the plan and term.</div></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">After payment, tell the seller your Chroma Client account and promo code, if you have one.</p></div><div><label className="mb-2 block text-xs font-semibold text-muted-foreground">Promo code (optional)</label><input value={promo} onChange={event => setPromo(event.target.value)} placeholder="CHROMA2026" className="h-11 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 text-sm outline-none placeholder:text-muted-foreground/50 focus:border-primary/60" /></div><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-between"><Button variant="ghost" onClick={() => setStep("method")} className="text-muted-foreground">Back</Button><Button onClick={() => openExternal(TELEGRAM_SELLER_URL)} className="h-11 rounded-xl bg-primary font-bold text-[#10150c]">Open Telegram <ArrowUpRight className="ml-2 h-4 w-4" /></Button></div><p className="text-xs leading-5 text-muted-foreground">In Telegram, tell the seller: <span className="font-semibold text-foreground">I’m from {promo ? `[${promo}]` : "[PROMO CODE]"}</span>.</p></div>}
      </div>
    </DialogContent>
  </Dialog>;
}
