ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('user','moderator','admin','owner','developer','support','media'));

INSERT INTO public.subscription_plans (name, slug, description, price, currency, duration_days, device_limit, features, active)
VALUES
  ('TESTER', 'tester', 'Custom testing access for QA accounts.', 0, 'RUB', 30, 3, '["Testing builds","QA access","Support priority"]'::jsonb, true),
  ('MEDIA', 'media', 'Custom media access for partners and creators.', 0, 'RUB', 30, 5, '["Media builds","Partner access","Creator support"]'::jsonb, true)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, duration_days = EXCLUDED.duration_days, device_limit = EXCLUDED.device_limit, features = EXCLUDED.features, active = true, updated_at = now();

CREATE TABLE IF NOT EXISTS public.support_tickets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_open_id uuid NOT NULL REFERENCES public.profiles(open_id) ON DELETE CASCADE,
  assignee_open_id uuid REFERENCES public.profiles(open_id) ON DELETE SET NULL,
  subject varchar(160) NOT NULL,
  category text NOT NULL CHECK (category IN ('subscription','bug','account','loader','other')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','pending','closed')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS support_tickets_user_open_id_idx ON public.support_tickets(user_open_id);
CREATE INDEX IF NOT EXISTS support_tickets_status_idx ON public.support_tickets(status);
CREATE INDEX IF NOT EXISTS support_tickets_updated_at_idx ON public.support_tickets(updated_at DESC);

CREATE TABLE IF NOT EXISTS public.support_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  author_open_id uuid NOT NULL REFERENCES public.profiles(open_id) ON DELETE CASCADE,
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  internal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS support_messages_ticket_id_idx ON public.support_messages(ticket_id, created_at);
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;
