CREATE TABLE IF NOT EXISTS public.support_auto_reply_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL,
  keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
  body text NOT NULL CHECK (char_length(body) BETWEEN 1 AND 5000),
  enabled boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 100,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS support_auto_reply_templates_enabled_idx ON public.support_auto_reply_templates(enabled, priority);
ALTER TABLE public.support_auto_reply_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS support_auto_reply_templates_staff_select ON public.support_auto_reply_templates;
CREATE POLICY support_auto_reply_templates_staff_select ON public.support_auto_reply_templates FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.open_id = auth.uid() AND p.role IN ('owner','developer','admin','support','moderator') AND p.status = 'active'));
INSERT INTO public.support_auto_reply_templates (name, keywords, body, priority) VALUES
('Приветствие', '["привет", "здравствуйте", "добрый день"]', 'Здравствуйте! Сообщение принято. Опишите проблему подробнее, и команда поддержки подключится.', 10),
('Ключ активации', '["ключ", "код", "активац"]', 'Проверьте, что код введён без пробелов и полностью заглавными буквами. Если ошибка повторяется, пришлите скриншот и текст ошибки.', 20),
('Подписка', '["подписк", "тариф", "base", "premium"]', 'Мы проверим состояние подписки и ответим в этом тикете. Укажите email аккаунта и название тарифа.', 30),
('Ошибка сайта', '["ошибка", "баг", "не работает", "сломалось"]', 'Спасибо за сообщение об ошибке. Пришлите шаги воспроизведения, браузер и скриншот — это ускорит исправление.', 40),
('Статус обращения', '["долго", "статус", "ответ"]', 'Обращение уже в очереди поддержки. Мы вернёмся с ответом в этом чате без необходимости обновлять страницу.', 50)
ON CONFLICT DO NOTHING;
